project_id = "ukjhomwsclrvpvpstipz"

[functions.veo3-video-gen]
verify_jwt = false

[functions.create-watermark-job]
verify_jwt = false

[functions.process-watermark-job]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.remove-image-watermark]
verify_jwt = false

[functions.google-stt]
verify_jwt = false

[functions.google-translate]
verify_jwt = false

[functions.google-dubbing]
verify_jwt = false

[functions.video-understanding]
verify_jwt = false
